version: '3.8'
services:
  mondial-db:
    image: postgres:17
    environment:
      POSTGRES_DB: mondial
      POSTGRES_USER: mondial
      POSTGRES_PASSWORD: mondial
    ports:
      - "5432:5432"

  mondial-jvm:
    image: mondial:latest
    ports:
      - "8080:8080"
    depends_on:
      - mondial-db
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://mondial-db:5432/mondial
      QUARKUS_DATASOURCE_USERNAME: mondial
      QUARKUS_DATASOURCE_PASSWORD: mondial
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: none